<?php
/**
 * Admin Image Review Queue
 * Variables: $images (array)
 */
?>
<div class="space-y-5">
    <div class="flex items-center justify-between">
        <h2 class="text-sm font-semibold text-white">Images Awaiting Review (
            <?= count($images) ?>)
        </h2>
        <p class="text-xs text-gray-400">AI-generated images that need human approval before going live</p>
    </div>

    <?php if (empty($images)): ?>
        <div class="bg-gray-900 border border-gray-800 rounded-xl text-center py-16 text-gray-500">
            <p class="text-4xl mb-3">🖼️</p>
            <p class="font-medium">No images awaiting review.</p>
            <p class="text-xs mt-1 text-gray-600">Images generated by n8n will appear here for approval.</p>
        </div>
    <?php else: ?>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
            <?php foreach ($images as $img): ?>
                <div class="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden flex flex-col">
                    <!-- Preview -->
                    <div class="aspect-video bg-gray-800 relative overflow-hidden">
                        <?php if (!empty($img['file_url'])): ?>
                            <img src="<?= htmlspecialchars($img['file_url']) ?>"
                                alt="<?= htmlspecialchars($img['alt_text'] ?? '') ?>" class="w-full h-full object-cover">
                        <?php else: ?>
                            <div class="w-full h-full flex items-center justify-center text-gray-600">
                                <i data-lucide="image" class="w-10 h-10"></i>
                            </div>
                        <?php endif; ?>
                        <span
                            class="absolute top-2 right-2 text-xs bg-yellow-700/80 text-yellow-200 px-2 py-0.5 rounded-full">Needs
                            Review</span>
                    </div>

                    <!-- Meta -->
                    <div class="p-3 flex-1 flex flex-col gap-2">
                        <?php if (!empty($img['alt_text'])): ?>
                            <p class="text-xs text-gray-300 line-clamp-2">
                                <?= htmlspecialchars($img['alt_text']) ?>
                            </p>
                        <?php endif; ?>
                        <?php if (!empty($img['ai_prompt'])): ?>
                            <p class="text-xs text-gray-600 italic line-clamp-2">"
                                <?= htmlspecialchars($img['ai_prompt']) ?>"
                            </p>
                        <?php endif; ?>
                        <div class="flex items-center gap-2 text-xs text-gray-500 mt-auto">
                            <span class="capitalize">
                                <?= htmlspecialchars($img['source_type'] ?? 'ai') ?>
                            </span>
                            <span>·</span>
                            <span>
                                <?= htmlspecialchars($img['image_slot'] ?? '') ?>
                            </span>
                        </div>
                        <div class="flex gap-2 mt-1">
                            <a href="<?= url('/admin/images/' . $img['id'] . '/approve') ?>"
                                class="flex-1 text-center text-xs bg-green-700 hover:bg-green-600 text-white py-1.5 rounded-lg transition-colors font-medium">
                                ✅ Approve
                            </a>
                            <a href="<?= url('/admin/images/' . $img['id'] . '/reject') ?>"
                                class="flex-1 text-center text-xs bg-red-900/60 hover:bg-red-800 text-red-300 py-1.5 rounded-lg transition-colors font-medium">
                                ❌ Reject
                            </a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>