<?php
declare(strict_types=1);

/**
 * RoadmapItem Model
 * Content generation queue: articles to be generated by n8n.
 */
class RoadmapItem
{
    /**
     * Returns paginated roadmap items, optionally filtered by status.
     *
     * @param string|null $status pending|queued|generating|published|failed|skipped
     * @param int         $page
     * @param int         $perPage
     * @return array{items: array, total: int, pages: int}
     */
    public static function getAll(?string $status = null, int $page = 1, int $perPage = 20): array
    {
        $offset = ($page - 1) * $perPage;
        $where = $status ? 'WHERE status = ?' : '';
        $params = $status ? [$status] : [];

        $total = (int) (Database::getInstance()->queryOne(
            "SELECT COUNT(*) AS cnt FROM roadmap_items $where",
            $params
        )['cnt'] ?? 0);

        $items = Database::getInstance()->query(
            "SELECT ri.*, c.name AS category_name
             FROM roadmap_items ri
             LEFT JOIN categories c ON ri.category_id = c.id
             $where
             ORDER BY ri.priority DESC, ri.created_at ASC
             LIMIT ? OFFSET ?",
            array_merge($params, [$perPage, $offset])
        );

        return ['items' => $items, 'total' => $total, 'pages' => (int) ceil($total / $perPage)];
    }

    /**
     * Returns the highest-priority pending roadmap item for a given content type.
     *
     * @param string $contentType blog|review|comparison|news
     * @return array|null
     */
    public static function getNextPending(string $contentType): ?array
    {
        return Database::getInstance()->queryOne(
            'SELECT ri.*, c.name AS category_name
             FROM roadmap_items ri
             LEFT JOIN categories c ON ri.category_id = c.id
             WHERE ri.content_type = ? AND ri.status = \'pending\'
             ORDER BY ri.priority DESC, ri.enrichment_count DESC, ri.created_at ASC
             LIMIT 1',
            [$contentType]
        );
    }

    /**
     * Creates a new roadmap item.
     *
     * @param array $data
     * @return int New ID
     */
    public static function create(array $data): int
    {
        $db = Database::getInstance();
        $db->execute(
            'INSERT INTO roadmap_items
             (title, slug, content_type, description, primary_keyword, secondary_keywords,
              search_intent, estimated_volume, keyword_difficulty, priority, category_id, source,
              knowledge_item_ids, status)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
            [
                $data['title'],
                $data['slug'],
                $data['content_type'],
                $data['description'] ?? null,
                $data['primary_keyword'],
                isset($data['secondary_keywords']) ? json_encode($data['secondary_keywords']) : null,
                $data['search_intent'] ?? 'informational',
                $data['estimated_volume'] ?? 0,
                $data['keyword_difficulty'] ?? 0,
                $data['priority'] ?? 50,
                $data['category_id'] ?? null,
                $data['source'] ?? 'manual',
                isset($data['knowledge_item_ids']) ? json_encode($data['knowledge_item_ids']) : null,
                $data['status'] ?? 'pending',
            ]
        );
        return $db->lastInsertId();
    }

    /**
     * Updates a roadmap item's fields.
     *
     * @param int   $id
     * @param array $data
     * @return void
     */
    public static function update(int $id, array $data): void
    {
        $allowed = [
            'title',
            'primary_keyword',
            'priority',
            'status',
            'description',
            'last_error',
            'retry_count',
            'knowledge_item_ids',
            'last_enriched_at',
            'article_id',
        ];
        $sets = [];
        $params = [];
        foreach ($data as $col => $val) {
            if (in_array($col, $allowed, true)) {
                $sets[] = "$col = ?";
                $params[] = $val;
            }
        }
        if (!$sets) {
            return;
        }
        $params[] = $id;
        Database::getInstance()->execute(
            'UPDATE roadmap_items SET ' . implode(', ', $sets) . ' WHERE id = ?',
            $params
        );
    }

    /**
     * Updates the status and optionally links the generated article ID.
     *
     * @param int      $id
     * @param string   $status
     * @param int|null $articleId
     * @return void
     */
    public static function updateStatus(int $id, string $status, ?int $articleId = null): void
    {
        Database::getInstance()->execute(
            'UPDATE roadmap_items SET status = ?, article_id = COALESCE(?, article_id) WHERE id = ?',
            [$status, $articleId, $id]
        );
    }

    /**
     * Increments enrichment count and links knowledge item IDs.
     *
     * @param int   $id
     * @param array $knowledgeItemIds
     * @return void
     */
    public static function incrementEnrichment(int $id, array $knowledgeItemIds): void
    {
        Database::getInstance()->execute(
            'UPDATE roadmap_items SET
             enrichment_count = enrichment_count + 1,
             last_enriched_at = NOW(),
             knowledge_item_ids = ?
             WHERE id = ?',
            [json_encode($knowledgeItemIds), $id]
        );
    }

    /**
     * Returns one roadmap item by ID.
     *
     * @param int $id
     * @return array|null
     */
    public static function getById(int $id): ?array
    {
        return Database::getInstance()->queryOne(
            'SELECT * FROM roadmap_items WHERE id = ? LIMIT 1',
            [$id]
        );
    }

    /**
     * Returns one non-failed roadmap item by slug.
     *
     * @param string $slug
     * @return array|null
     */
    public static function getBySlugActive(string $slug): ?array
    {
        return Database::getInstance()->queryOne(
            'SELECT * FROM roadmap_items WHERE slug = ? AND status != \'failed\' LIMIT 1',
            [$slug]
        );
    }

    /**
     * Marks a roadmap item as generating.
     *
     * @param int $id
     * @return void
     */
    public static function markGenerating(int $id): void
    {
        Database::getInstance()->execute(
            'UPDATE roadmap_items SET status = \'generating\', last_error = NULL WHERE id = ?',
            [$id]
        );
    }

    /**
     * Marks generation failure and increments retry_count.
     *
     * @param int    $id
     * @param string $error
     * @param int    $maxRetries
     * @return void
     */
    public static function markFailed(int $id, string $error, int $maxRetries = 3): void
    {
        Database::getInstance()->execute(
            'UPDATE roadmap_items
             SET retry_count = retry_count + 1,
                 last_error = ?,
                 status = CASE WHEN retry_count + 1 >= ? THEN \'failed\' ELSE \'pending\' END
             WHERE id = ?',
            [mb_substr($error, 0, 1000), $maxRetries, $id]
        );
    }

    /**
     * Finds semantically similar roadmap items by keyword similarity.
     * Uses word overlap to detect near-duplicates.
     *
     * @param string $keyword
     * @param string $contentType
     * @param float  $threshold  Similarity threshold (0.0-1.0)
     * @return array|null The most similar item, or null
     */
    public static function findSimilar(string $keyword, string $contentType, float $threshold = 0.6): ?array
    {
        $candidates = Database::getInstance()->query(
            "SELECT id, title, slug, primary_keyword, knowledge_item_ids, status
             FROM roadmap_items
             WHERE content_type = ? AND status NOT IN ('published', 'failed', 'skipped')
             ORDER BY created_at DESC LIMIT 200",
            [$contentType]
        );

        $inputWords = array_unique(array_filter(
            preg_split('/[\s\-_]+/', mb_strtolower(trim($keyword))),
            static fn(string $w): bool => mb_strlen($w) > 2
        ));

        if (empty($inputWords)) {
            return null;
        }

        $bestMatch = null;
        $bestScore = 0.0;

        foreach ($candidates as $candidate) {
            $candidateText = mb_strtolower(trim(($candidate['primary_keyword'] ?? '') . ' ' . ($candidate['title'] ?? '')));
            $candidateWords = array_unique(array_filter(
                preg_split('/[\s\-_]+/', $candidateText),
                static fn(string $w): bool => mb_strlen($w) > 2
            ));

            if (empty($candidateWords)) {
                continue;
            }

            $intersection = count(array_intersect($inputWords, $candidateWords));
            $union = count(array_unique(array_merge($inputWords, $candidateWords)));
            $jaccard = $union > 0 ? $intersection / $union : 0.0;

            if ($jaccard > $bestScore) {
                $bestScore = $jaccard;
                $bestMatch = $candidate;
            }
        }

        return ($bestMatch && $bestScore >= $threshold) ? $bestMatch : null;
    }

    /**
     * Approves a needs_review item (sets status to pending).
     *
     * @param int $id
     * @return void
     */
    public static function approve(int $id): void
    {
        Database::getInstance()->execute(
            "UPDATE roadmap_items SET status = 'pending' WHERE id = ? AND status = 'needs_review'",
            [$id]
        );
    }

    /**
     * Rejects a needs_review item (sets status to skipped).
     *
     * @param int $id
     * @return void
     */
    public static function reject(int $id): void
    {
        Database::getInstance()->execute(
            "UPDATE roadmap_items SET status = 'skipped' WHERE id = ? AND status = 'needs_review'",
            [$id]
        );
    }

    /**
     * Bulk-approves needs_review items.
     *
     * @param array $ids
     * @return void
     */
    public static function bulkApprove(array $ids): void
    {
        $clean = array_values(array_filter(array_map('intval', $ids), static fn(int $id): bool => $id > 0));
        if (!$clean) {
            return;
        }
        $placeholders = implode(',', array_fill(0, count($clean), '?'));
        Database::getInstance()->execute(
            "UPDATE roadmap_items SET status = 'pending' WHERE id IN ({$placeholders}) AND status = 'needs_review'",
            $clean
        );
    }

    /**
     * Bulk-rejects needs_review items.
     *
     * @param array $ids
     * @return void
     */
    public static function bulkReject(array $ids): void
    {
        $clean = array_values(array_filter(array_map('intval', $ids), static fn(int $id): bool => $id > 0));
        if (!$clean) {
            return;
        }
        $placeholders = implode(',', array_fill(0, count($clean), '?'));
        Database::getInstance()->execute(
            "UPDATE roadmap_items SET status = 'skipped' WHERE id IN ({$placeholders}) AND status = 'needs_review'",
            $clean
        );
    }

    /**
     * Returns item counts grouped by status.
     *
     * @return array<string, int>
     */
    public static function countByStatus(): array
    {
        $rows = Database::getInstance()->query(
            'SELECT status, COUNT(*) AS cnt FROM roadmap_items GROUP BY status'
        );
        $result = [];
        foreach ($rows as $row) {
            $result[$row['status']] = (int) $row['cnt'];
        }
        return $result;
    }
}
